<?php 
	define('ENTERPRISE_NAME1', 'Amicus de México, S.A. de C.V.');
	define('ENTERPRISE_RFC1', 'AME020530SA4');
	define('ENTERPRISE_REGPAT1', 'Y6441835102');
	define('ENTERPRISE_BOSS1', 'LIC. MARÍA A. ESCAMILLA MOHEDANO');

	define('ENTERPRISE_NAME2', 'Amicus Marketing, S.A. de C.V.');
	define('ENTERPRISE_RFC2', 'AMA170424IQ0');
	define('ENTERPRISE_REGPAT2', 'Z3912735100');
	define('ENTERPRISE_BOSS2', 'L. LAURA ORTEGA ESCAMILLA');
?>